Intro Python

In [1]:
import time
print(time.ctime())

Wed Feb 23 14:51:07 2022


In [3]:
x = x + 1
print("Angka X Adalah :",x)

Angka X Adalah : 3


In [2]:
x = 1
y = x + 1
x = 2
print("Angka Y Adalah :",y)

Angka Y Adalah : 2


Intro Numpy

In [2]:
import numpy as np

In [7]:
x = np.array([1, 4, 3])
print("Array X Adalah :")
print(x)

Array X Adalah :
[1 4 3]


In [8]:
y = np.array([[1, 4, 3], [9, 2, 7]])
print("Array Y Adalah :")
print(y)

Array Y Adalah :
[[1 4 3]
 [9 2 7]]


Intro IF Else

In [16]:
def myThermoStat(temp, desTemp):
    if temp < desTemp - 5:
      status = 'Heat'
    elif temp > desTemp + 5:
      status = 'AC'
    else:
      status = 'OFF'
    return status

In [19]:
status = myThermoStat(65,75)
print(status)

Heat


In [18]:
status = myThermoStat(75,65)
print(status)

AC


In [17]:
status = myThermoStat(65,63)
print(status)

OFF


In [14]:
x = 3
if x > 1 and x < 2:
    y = 2
elif x > 2 and x < 4:
    y = 4
else:
    y = 0

print(y)

4


In [11]:
def my_adder (a,b,c):
  """
  function to sum the 3 numbers
  input: 3 numbers a, b, c
  Output: the sum of a, b, and c
  author: Rifaldi Indrajaya
  date: 23/02/2022
  """

  #this is the summation
  out = a + b + c

  return out

In [13]:
my_adder(4,5,6)

15

In [12]:
help(my_adder)

Help on function my_adder in module __main__:

my_adder(a, b, c)
    function to sum the 3 numbers
    input: 3 numbers a, b, c
    Output: the sum of a, b, and c
    author: Rifaldi Indrajaya
    date: 23/02/2022



Mencoba Fungsi

In [9]:
##function sum matrix two dimentional

def sum_matrix(matrix):
    sum = 0
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            sum += matrix[i][j]
    return sum

##funtion bubble sort

def bubble_sort(arr):
    for i in range(len(arr)):
        for j in range(len(arr)-1-i):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

In [7]:
sum_matrix([[1,2,3],[4,5,6]])

21

In [10]:
bubble_sort([10,2,12,4,87,6])

[2, 4, 6, 10, 12, 87]